<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup>
    <None Include="SplayTree.cs" />
    <None Include="RedBlackTree.cs" />
    <None Include="Entry.cs" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="AVLTree.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="HugeListBase.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TreeLibInterface\TreeLibInterface.csproj" />
  </ItemGroup>
</Project>