<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <DocumentationFile>bin\Debug\TreeLib.XML</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <DocumentationFile>bin\Release\TreeLib.XML</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TreeLibInterface\TreeLibInterface.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="transform.xml" />
  </ItemGroup>
  <PropertyGroup />
</Project>